version: '2.2'
volumes:
  pgdata:
    driver: local
services:
  reporting-db:
    build:
      context: ./
      dockerfile: DockerfilePostgres
    container_name: reporting-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=scalable
      - POSTGRES_PASSWORD=capital
      - POSTGRES_DB=reporting
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
  scalable-capital-reporting-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_IDENTIFIER=SCR
      - HOST=0.0.0.0
      - PORT=8080
      - MAX_WORKERS=4
      - MAX_REQUESTS=100
      - DB_USER=scalable
      - DB_PWD=capital
      - DB_NAME=reporting
      - DB_PORT=5432
      - DB_HOST=reporting-db
    mem_limit: 4gb
    depends_on:
      - reporting-db
    ports:
      - "8080:8080"